version: '3.8'

services:
  laravel:
    image: ambientum/php:latest-nginx
    container_name: laravel
    ports:
      - 8080:8000
    external_links:
      - postgres:5432
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=rgn
      - DB_DATABASE=portfolio
      - DB_PASSWORD=123456
    volumes:
      - /var/www/app:/var/www/app

networks:
  default:
    external:
      name: portfolio